name: Gntics
markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title
gems: ["jekyll-assets"]
exclude: ["Guardfile", "Gemfile", "Gemfile.lock", "deploy_to_master.sh", "Rakefile", "todo", "tmp.json"]
assets:
  dirname: assets
  baseurl: /assets/
  gzip: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
